#!/bin/sh
WHO=$(logname 2>/dev/null)
if [[ "${WHO}" == "" ]]
then
        WHO=$(whoami)
fi
STAMP=${WHO}.$(date "+%Y%m%d%H%M%S")
if [[ $# -eq 1 ]]
then
        if [[ -e "$1" ]]
        then
                if [[ -d "$1" ]]
                then
                        echo "Copying \"$1\" to \"$1.${STAMP}\""
                        cp -pr "$1" "$1.${STAMP}"
                else
                        echo "Copying \"$1\" to \"$1.${STAMP}\""
                        cp -p "$1" "$1.${STAMP}"
                fi
        else
                echo "ERROR: \"$1\" does not exist"
        fi
else
        echo "ERROR: Incorrect number of parameters"
        echo
        echo "Usage: $0 [file||directory]"
fi

